In [119]:
import numpy as np
from scipy.stats import norm
import math
from scipy.optimize import minimize_scalar, minimize
from pathlib import Path
import time
from PIL import Image
import matplotlib.pyplot as plt
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

%config InlineBackend.figure_formats = 'svg'

In [120]:
@dataclass
class OptimizationResults:
    """
    optimization_history:
        'opt_name'
        'history_x'
        'history_loss'
        'bounds'
        'loss_mode'
        'loss_func'
        'target_width'
        'l_gray': l_gray
    """
    La: float
    optimization_history: dict[str, Any] | None = None

    def optimization_visualization(self, ax: plt.Axes, num_points: int = 200, x_log_scale: bool = False):
        if self.optimization_history is None:
            raise RuntimeError('История оптимизации пуста')

        space = np.linspace(*self.optimization_history['bounds'], num=num_points)
        loss_landscape = [self.optimization_history['loss_func'](x) for x in space]
        optimal_loss = self.optimization_history['loss_func'](np.log(self.La))

        step_numbers = list(range(1, len(self.optimization_history['history_x']) + 1))

        scatter = ax.scatter(
            np.exp(self.optimization_history['history_x']), 
            self.optimization_history['history_loss'],

            cmap='plasma',
            c=step_numbers,
            s=30,
            alpha=0.75,
            zorder=3,
            label='Шаги оптимизатора'
        )

        ax.scatter(
            self.La, 
            optimal_loss,
            color='red',
            marker='*',
            s=100,
            edgecolor='black',
            linewidth=1.0,
            zorder=4,
            alpha=0.75,
            label=f'Найденная La = {self.La:.2f}'
        )

        ax.plot(
            np.exp(space), 
            loss_landscape,
            label='Функция потерь'
        )

        ax.set(
            xlabel='Яркость в линейном масштабе',
            ylabel='Loss',
            title=f"График {self.optimization_history['opt_name']} c loss_mode = {self.optimization_history['loss_mode']}"
        )

        cbar = ax.figure.colorbar(scatter, ax=ax)
        cbar.set_label('Номер шага')

        ax.legend(
            loc='best',
            fontsize=9
        )

        if x_log_scale:
            ax.set_xscale('log')
            ax.set_xlabel('Яркость в логарифмическом масштабе')

In [121]:
class SimkinJNDModel:

    def __init__(self, L_MIN = 0.1, L_MAX = 300, screen_diag_inch = 16, screen_width_px = 1920, 
                screen_height_px = 1080, distance_m = 0.5, l_gray = 60):
        
        self.L_MIN = L_MIN
        self.L_MAX = L_MAX
        self.L0 = 1e-6

        diag_px = math.sqrt(screen_width_px ** 2 + screen_height_px ** 2)
        ppi = diag_px / screen_diag_inch
        
        pixel_size_m = 0.0254 / ppi # 1 дюйм = 0.0254 метра

        self.phi_screen = pixel_size_m / distance_m # считаем угловой размер пикселя на экране
        self.phi = self.phi_screen
        
        self.screen_width_px = screen_width_px
        self.screen_height_px = screen_height_px
        self.ppi = ppi
        self.l_gray = l_gray

    def _Simkin_A(self, La: float | np.ndarray) -> float | np.ndarray:
        a1: float = 4800000.0
        a2: float = 7100.0
        a3: float = 0.00045
        return 1.0 + np.sqrt(a1 * La) + a2 * La * (1.0 + np.sqrt(a3 * La))

    def _Simkin_l(self, La: float | np.ndarray) -> float | np.ndarray:
        L0: float = 0.000001
        return L0 * self._Simkin_A(La)

    def _Simkin_lambda(self, L: np.ndarray | float, La: float | np.ndarray) -> np.ndarray | float:
        Xao: float = 100.0
        return L / (Xao * self._Simkin_l(La))

    def _Simkin_LAt(self, lambda_: np.ndarray | float) -> np.ndarray | float:
        b1: float = 0.98
        b2: float = 0.1
        lambda1: float = 0.02
        lambda_arr = np.asarray(lambda_, dtype=np.float64)
        return np.where(lambda_arr <= 1.0, b1 * (lambda_arr + lambda1), lambda_arr ** (1.0 + b2))

    def _Simkin_ro(self, La: float | np.ndarray) -> float | np.ndarray:
        L1: float = 10.0
        L2: float = 0.000026
        c2: float = 0.25
        return (1.0 + L1 / (L2 + La)) ** c2

    def _Simkin_teta(self, phi: float, La: float | np.ndarray) -> float | np.ndarray:
        phi_omin: float = (1.0 / 60.0) * np.pi / 180.0
        return phi / (phi_omin * self._Simkin_ro(La))

    def _Simkin_S(self, teta: float) -> float:
        teta1: float = 6.1
        return (teta1 / teta + 1.0) ** 2

    def _simkin_nu(self, La: float | np.ndarray) -> float | np.ndarray:
        nu = 4.1 - 3.4 / (1.0 + np.exp(-0.5 - np.log10(La)))
        return np.clip(nu, 1.0, 4.0)

    def _simkin_T(self, t: float, La: float | np.ndarray) -> float | np.ndarray:
        return t / (0.05 * self._simkin_nu(La))

    def _simkin_C(self, T: float) -> float:
        return 1.0 + 1.0 / T

    def _Simkin_fN(self, La: float | np.ndarray, L: np.ndarray | float, LN: float) -> np.ndarray | float:
        sigma_N = 3.0 * LN / self._Simkin_l(La)
        lat_val = self._Simkin_LAt(self._Simkin_lambda(L, La))
        return np.sqrt(1.0 + (sigma_N * sigma_N) / (lat_val * lat_val))

    def _simkin_core(
        self,
        La: float | np.ndarray,
        L: np.ndarray | float,
        phi: float | None = None,
        LN: float = 0.0,
        t: float = 1
    ) -> np.ndarray | float:
        
        if phi is None:
            phi = self.phi

        return (
            self.L0
            * self._Simkin_A(La)
            * self._Simkin_LAt(self._Simkin_lambda(L, La))
            * self._Simkin_S(self._Simkin_teta(phi, La))
            * self._Simkin_fN(La, L, LN)
            * self._simkin_C(self._simkin_T(t, La))
        )

    def find_median(self, L_patch: np.ndarray, target_width: float | str) -> float:
        _, n_total, n_patch_screen, n_bg = self._compute_screen_geometry(L_patch=L_patch, target_width=target_width)

        if n_bg > 0:
            boundaries = (min(self.l_gray, np.min(L_patch)), max(self.l_gray, np.max(L_patch)))
        else:
            boundaries = (np.min(L_patch), np.max(L_patch))

        bins_count = 1024
        hist, bin_edges = np.histogram(L_patch.ravel(), bins=bins_count, range=boundaries)

        hist = hist.astype(np.float64)
        hist *= (n_patch_screen / L_patch.size)

        if n_bg > 0:
            bg_bin = int(np.clip(np.searchsorted(bin_edges, self.l_gray, side='right') - 1, 0, len(hist) - 1))
            hist[bg_bin] += n_bg 

        cdf = np.cumsum(hist)

        median_bin_idx = int(np.searchsorted(cdf, n_total / 2.0))
        median_bin_idx = min(median_bin_idx, bins_count - 1)

        median_val = (bin_edges[median_bin_idx] + bin_edges[median_bin_idx + 1]) / 2.0

        return median_val

    def _compute_screen_geometry(self, L_patch: np.ndarray, target_width: float | str) -> tuple:
        n_patch = L_patch.size
        h_patch_px, w_patch_px = L_patch.shape

        if target_width == 'full':
            phi = self.phi_screen
            n_total = n_patch
            n_patch_screen = n_patch
            n_bg = 0
        elif target_width == 'orig':
            phi = self.phi_screen
            n_total = self.screen_height_px * self.screen_width_px
            n_patch_screen = n_patch
            n_bg = n_total - n_patch
        else:
            aspect_ratio = h_patch_px / w_patch_px
            target_w_px = int(np.round((target_width / 2.54) * self.ppi)) # вычисление количества пикселей, которое будет
            target_h_px = int(np.round(target_w_px * aspect_ratio))       # занимать отмаштабированное изображение на экране

            n_total = self.screen_height_px * self.screen_width_px
            n_patch_screen = target_w_px * target_h_px

            n_bg = n_total - n_patch_screen

            scale = target_w_px / w_patch_px
            phi = scale * self.phi_screen

            if target_w_px > self.screen_width_px or target_h_px > self.screen_height_px:
                raise ValueError(
                    f"При target_width = {target_width} см размер патча ({target_w_px}x{target_h_px} px) "
                    f"превышает экран ({self.screen_width_px}x{self.screen_height_px} px)"
                )

        if n_bg < 0:
            raise ValueError(
                f'При текущем target_width = {target_width}, количество пикселей изображения = {n_patch_screen}' 
                f'больше количества пикселей на экране = {n_total}'
            )

        return phi, n_total, n_patch_screen, n_bg

    def _get_search_bounds(self, L_patch: np.ndarray, has_background: bool) -> tuple[float, float]:
        if L_patch.size == 0: # если берем в рассчет только фон (для проверки честного поиска La)
            return float(np.log(self.L_MIN)), float(np.log(self.L_MAX))
        
        La_min = max(np.min(L_patch), self.L_MIN)
        log_La_min = np.log(La_min)
        La_max = min(np.max(L_patch), self.L_MAX)
        log_La_max = np.log(La_max)

        if has_background:
            log_bg = np.log(self.l_gray)
            log_La_min = min(log_La_min, log_bg)
            log_La_max = max(log_La_max, log_bg)

        if log_La_min >= log_La_max:
            log_La_min -= 1e-4
            log_La_max += 1e-4

        return float(log_La_min), float(log_La_max)

    def _build_loss_func(
        self, 
        L_patch: np.ndarray, 
        n_total: int, 
        n_patch_screen: int, 
        n_bg: int,  
        loss_mode: str
    ) -> Callable[[float], float]:
        
        has_background = n_bg > 0
        has_patch = n_patch_screen > 0

        patch_weight = (n_patch_screen / L_patch.size) if has_patch else 0.0

        bg_weight = n_bg

        den_patch = self._simkin_core(La=L_patch, L=L_patch) if has_patch else None
        den_bg = self._simkin_core(La=self.l_gray, L=self.l_gray) if has_background else None

        if loss_mode == 'abs':
            loss_patch = lambda x: float(np.sum(np.abs(np.log(x))))
            loss_bg = lambda x: abs(math.log(x))
        elif loss_mode == 'square':
            loss_patch = lambda x: float(np.sum(np.square(np.log(x))))
            loss_bg = lambda x: math.log(x) ** 2
        else:
            raise ValueError(f"Неизвестный loss_mode: {loss_mode}")

        def objective_log_La(log_La: float) -> float:
            curr_La = math.exp(log_La)
            total_loss = 0.0

            if has_patch:
                num_patch = self._simkin_core(La=curr_La, L=L_patch)
                total_loss += patch_weight * loss_patch(num_patch / den_patch)

            if has_background:
                num_bg = self._simkin_core(La=curr_La, L=self.l_gray)
                total_loss += bg_weight * loss_bg(num_bg / den_bg)

            return total_loss / n_total

        return objective_log_La

    def _run_optimizer(
        self, 
        loss_func: Callable[[float], float],
        bounds: tuple[float, float], 
        optimizer: str, 
        loss_mode: str,
        target_width: float | str,
        visualization: bool = False,
        **optimizer_kwargs: Any
    ) -> OptimizationResults:

        history_x = []
        history_loss = []
        
        if optimizer == 'minimize_scalar':

            def tracked_objective(log_la):
                loss = loss_func(log_la)
                history_x.append(float(log_la))
                history_loss.append(float(loss))
                return loss

            result = minimize_scalar(
                tracked_objective,
                bounds=bounds,
                method='bounded',
                options={'xatol': 1e-6},
            )

            self.La = math.exp(float(result.x))

        elif optimizer == 'log_grid_search':

            log_space = np.linspace(*bounds, num=100)

            best_la = 0
            min_loss = 1e10

            for log_la in log_space:
                loss = loss_func(log_la)

                history_x.append(log_la)
                history_loss.append(loss)

                if min_loss > loss:
                    min_loss = loss
                    best_la = np.exp(log_la)

            self.La = best_la

        elif optimizer == 'L-BFGS-B':
            x0 = optimizer_kwargs.get('x0', None)
            init_x = x0 if x0 is not None else 0.5 * (bounds[0] + bounds[1])

            def tracked_objective(x: np.ndarray) -> float:
                loss = loss_func(float(x[0]))
                history_x.append(float(x[0]))
                history_loss.append(float(loss))
                return loss

            result = minimize(
                fun=tracked_objective,
                x0=np.array([init_x]),
                bounds=[bounds],
                method='L-BFGS-B',
                options={'ftol': 1e-9}
            )

            self.La = math.exp(float(result.x[0]))

        elif optimizer == 'oscillating_optimizer':
            max_reversals = optimizer_kwargs.get('max_reversals', 2)
            step = optimizer_kwargs.get('step', 0.1)
            step_reduction = optimizer_kwargs.get('step_reduction', 10.0)
            start_La = optimizer_kwargs.get('start_La', None)
            max_iters = optimizer_kwargs.get('max_iters', 100)

            if start_La is None:
                raise ValueError('Начальная точка для oscillating_optimizer не задана')

            curr_La = start_La
            best_La = curr_La
            best_loss = loss_func(math.log(curr_La))
            prev_loss = best_loss

            reversals = 0
            direction = 1
            iterations = 0

            history_loss.append(best_loss)
            history_x.append(math.log(best_La))

            while reversals <= max_reversals and iterations < max_iters:
                iterations += 1

                if direction == 1:
                    next_La = curr_La * (1.0 + step)
                    if next_La > math.exp(bounds[1]):
                        break
                else:
                    next_La = curr_La / (1.0 + step)
                    if next_La < math.exp(bounds[0]):
                        break

                curr_La = next_La
                curr_loss = loss_func(math.log(curr_La))

                if curr_loss < best_loss:
                    best_loss = curr_loss
                    best_La = curr_La

                if curr_loss > prev_loss:
                    direction *= -1
                    reversals += 1
                    step /= step_reduction

                prev_loss = curr_loss

                history_loss.append(curr_loss)
                history_x.append(math.log(curr_La))

            self.La = best_La
        
        else:
            raise ValueError('Неизвестный оптимизатор')

        optimization_history = {
            'opt_name': optimizer,
            'history_x': history_x,
            'history_loss': history_loss,
            'bounds': bounds,
            'loss_mode': loss_mode,
            'loss_func': loss_func,
            'target_width': target_width,
            'l_gray': self.l_gray
        } if visualization else None
        
        return OptimizationResults(La=self.La, optimization_history=optimization_history)

    def find_La(self, 
        L_patch: np.ndarray | float, 
        target_width: float | str, 
        optimizer: str, 
        loss_mode: str, 
        visualization: bool = False,
        **optimizer_params: Any
    ) -> OptimizationResults:
        
        """
        Параметры:
            L_patch (подается в оригинальном разрешении)

            target_width - желаемая ширина изображения в сантиметрах, либо же параметр (full или orig)
                full - изображение "на весь экран" без фона, но угловой размер берем от реального дисплея
                orig - изображение в исходном разрешении, все остальное заливается фоном

            optimizer - желаемый оптимизатор
                minimize_scalar
                log_grid_search
                L-BFGS-B
                    x0 - численная начальная точка
                oscillating_optimizer
                    max_reversals - максимальное количество переворотов
                    step - шаг оптимизатора (изменение La каждый раз в 1 + step раз)
                    step_reduction - изменение шага в step_reduction раз после каждого переворота
                    start_La - начальная La
                    max_iters - максимальное количество итераций оптимизатора
            
            loss_mode - желаемая loss функция
                square
                abs
            
            visualization - нужна ли визуализация графиков оптимизации
                True
                False

        Возвращает:
            OptimizationResults - объект датакласса с найденной яркостью адаптации и результатами оптимизации
        """

        if isinstance(L_patch, (int, float)):
            L_patch = np.array([[L_patch]])

        phi, n_total, n_patch_screen, n_bg = self._compute_screen_geometry(L_patch=L_patch, target_width=target_width)
        self.phi = phi
        bounds = self._get_search_bounds(L_patch=L_patch, has_background=(n_bg > 0))

        loss_func = self._build_loss_func(
            L_patch=L_patch,
            n_total=n_total,
            n_patch_screen=n_patch_screen,
            n_bg=n_bg,
            loss_mode=loss_mode
        )

        La = self._run_optimizer(
            loss_func=loss_func, 
            bounds=bounds, 
            optimizer=optimizer,
            loss_mode=loss_mode,
            target_width=target_width,
            visualization=visualization,
            **optimizer_params
        )

        return La

    def build_level_boundaries(self):
        L_right_bounds = []
        L_curr = self.La
        while L_curr < self.L_MAX:
            L_curr += self._simkin_core(L = L_curr, La = self.La)
            L_right_bounds.append(min(L_curr, self.L_MAX))

        L_left_bounds = []
        L_curr = self.La
        while L_curr > self.L0:
            L_curr -= self._simkin_core(L = L_curr, La = self.La)
            L_left_bounds.append(max(L_curr, self.L0))

        self.len_left = len(L_left_bounds)

        L_left_bounds.reverse()

        self.bounds = np.array(L_left_bounds + [self.La] + L_right_bounds)

        return self.bounds

    def L_to_k(self, L): # всегда берем нижнюю границу интервала, в который попали
        idx = np.searchsorted(self.bounds, L, side='right') - 1
        idx = np.clip(idx, 0, len(self.bounds) - 1)
        return idx - self.len_left
        
    def k_to_L(self, k): # всегда берем нижнюю границу интервала, в который попали
        return self.bounds[k + self.len_left]

In [122]:
class ImageConverter:
    def __init__(self, L_MIN: float = 0.1, L_MAX: float = 300):

        self.M = np.array([
            [0.4124564,  0.3575761,  0.1804375],
            [0.2126729,  0.7151522,  0.0721750],
            [0.0193339,  0.1191920,  0.9503041]
        ])
        self.M_inv = np.array([
            [ 3.1338561, -1.6168667, -0.4906146],
            [-0.9787684,  1.9161415,  0.0334540],
            [ 0.0719453, -0.2289914,  1.4052427]
        ])

        self.L_MAX = L_MAX
        self.L_MIN = L_MIN
        self.coord_white = np.array([0.3127, 0.3290, 0.3583])
        self.eps = 1e-10

    def sRGB_Companding(self, linear_image: np.ndarray) -> np.ndarray:
        linear = np.clip(np.asarray(linear_image, dtype=np.float64), 0.0, 1.0)
        
        encoded = np.where(
            linear <= 0.0031308,
            linear * 12.92,
            1.055 * (linear ** (1.0 / 2.4)) - 0.055
        )
        return encoded

    def Inverse_sRGB_Companding(self, image: np.ndarray) -> np.ndarray:
        img = np.asarray(image, dtype=np.float64)
        
        linear = np.where(
            img <= 0.04045,
            img / 12.92,
            ((img + 0.055) / 1.055) ** 2.4
        )
        return linear

    def Linear_RGB_to_XYZ(self, image: np.ndarray) -> np.ndarray:
        XYZ_image = image.reshape(-1, 3)
        return (XYZ_image @ self.M.T).reshape(image.shape)

    def XYZ_to_xyzL(self, XYZ_image: np.ndarray) -> np.ndarray:
        """
        Возвращает тензор (H, W, С), С = 4 (x, y, z, L)
        """
        sum_xyz = XYZ_image.sum(keepdims=True, axis=-1)

        xyz = XYZ_image / (sum_xyz + self.eps)
        
        is_black = (sum_xyz < self.eps).squeeze(-1) 

        if np.any(is_black):
            xyz[is_black] = self.coord_white

        Y = XYZ_image[..., 1]

        L_norm = np.clip(Y, 0.0, 1.0)

        L_physical = self.L_MIN + L_norm * (self.L_MAX - self.L_MIN)

        L_physical = np.expand_dims(L_physical, axis=-1)

        xyzL = np.concatenate([xyz, L_physical], axis=-1) # (H, W, С) С = 4 (x, y, z, L)

        return xyzL

    def RGB_to_xyzL(self, image: np.ndarray) -> np.ndarray:
        """
        На вход изображение - ненормализованный тензор RGB
        Возвращается тензор (x, y, z, L). L - физическая яркость на основе параметров монитора, в диапазоне (L_MIN, L_MAX)
        """
    
        # [0, 1]
        norm_img = np.asarray(image, dtype=np.float64) / 255.0
    
        # sRGB -> linRGB
        linRGBimg = self.Inverse_sRGB_Companding(norm_img)
    
        #linRGB -> XYZ
        XYZ_image = self.Linear_RGB_to_XYZ(linRGBimg)
    
        xyzL_image = self.XYZ_to_xyzL(XYZ_image)

        return xyzL_image

    def L_to_gray(self, L: np.ndarray | float) -> np.ndarray | np.uint8:
        """
        На вход L - число или матрица ненормированных яркостей
        Возвращается матрица или число (np.uint8) со значениями в градациях серого (от 0 до 255)
        """

        Y_lin = (L - self.L_MIN) / (self.L_MAX - self.L_MIN)

        Y_lin = np.clip(Y_lin, 0.0, 1.0)

        V = self.sRGB_Companding(Y_lin)

        gray_matrix = np.rint(V * 255).astype(np.uint8)

        return gray_matrix

In [123]:
jnd_model = SimkinJNDModel()
converter = ImageConverter()

In [124]:
dark = []
bright = []

dark_path = Path('results/plots/dark')
bright_path = Path('results/plots/bright')
uniform_path = Path('results/plots/uniform')

dark_path.mkdir(parents=True, exist_ok=True)
bright_path.mkdir(parents=True, exist_ok=True)
uniform_path.mkdir(parents=True, exist_ok=True)

In [125]:
from itertools import product
import pandas as pd

img_paths = [Path('../examples/bright.jpg'), Path('../examples/dark.jpg')]

for i, img_path in enumerate(img_paths):

    image = Image.open(img_path)

    np_image = np.array(image)

    xyzL = converter.RGB_to_xyzL(np_image)

    L_patch = xyzL[..., -1]

    for l_gray, loss_mode, target_width in product(
        [30, 60, 90], 
        ['abs', 'square'], 
        ['orig','full', 4, 8, 15]
    ):
        jnd_model.l_gray = l_gray

        fig, axes = plt.subplots(2, 2, figsize=(14, 10), layout='constrained')

        fig.suptitle(
            f'Сравнение оптимизаторов. Фон L_gray = {l_gray} | Loss_mode = {loss_mode} | Размер патча = {target_width}',
            fontsize=12
        )

        _, _, n_patch_screen, n_bg = jnd_model._compute_screen_geometry(L_patch=L_patch, target_width=target_width)

        start_La = min(np.min(L_patch), l_gray) if target_width != 'full' else np.min(L_patch)
        median = jnd_model.find_median(L_patch=L_patch, target_width=target_width)

        optimizers = [
            {
                'name': 'minimize_scalar'
            },
            {
                'name': 'L-BFGS-B',
                'params': {'x0': median}
            },
            {
                'name': 'log_grid_search'
            },
            {
                'name': 'oscillating_optimizer',
                'params': {
                    'max_reversals': 5,
                    'step': 0.1,
                    'step_reduction': 5,
                    'start_La': start_La,
                    'max_iters': 100
                }
            }
        ]


        for idx, optimizer in enumerate(optimizers):
            ax = axes.flat[idx]

            optimization_results = jnd_model.find_La(
                L_patch,
                target_width=target_width, 
                loss_mode=loss_mode, 
                optimizer=optimizer['name'], 
                visualization=True,
                **optimizer.get('params', {})
            )

            optimization_results.optimization_visualization(ax=ax, x_log_scale=False)

            jnd_model.build_level_boundaries()

            res_entry = {
                'Средняя яркость патча': L_patch.mean(),
                'Яркость фона': l_gray,
                'Оптимизатор': optimizer['name'],
                'optimize mode': loss_mode,
                'Размер патча, см': target_width,
                'Кол-во уровней': len(jnd_model.bounds),
                'La': jnd_model.La
            }

            if i == 0:
                bright.append(res_entry)
            else:
                dark.append(res_entry)

        category = 'bright' if i == 0 else 'dark'

        save_dir = Path('results/plots') / category / f'L_gray_{l_gray}' / f'loss_mode_{loss_mode}' / f'target_width_{target_width}'
        save_dir.mkdir(parents=True, exist_ok=True)

        fig.savefig(save_dir / 'linear.png', dpi=300, bbox_inches='tight', pad_inches=0.2)

        for ax in axes.flat:
            ax.set_xscale('log')
            ax.set_xlabel('Яркость в логарифмическом масштабе')

        fig.savefig(save_dir / 'log.png', dpi=300, bbox_inches='tight', pad_inches=0.2)

        plt.close(fig)

In [136]:
uniform = []

width, height = 256, 256
total_pixels = width * height

num_levels = 256
repeats_per_level = total_pixels // num_levels

levels = np.linspace(jnd_model.L_MIN, jnd_model.L_MAX, 256, dtype=np.float64)

L_patch = np.repeat(levels, repeats_per_level)

L_patch = L_patch.reshape((height, width))

for l_gray, loss_mode, target_width in product(
    [30, 60, 90], 
    ['abs', 'square'], 
    ['orig','full', 4, 8, 15]
):
    jnd_model.l_gray = l_gray

    fig, axes = plt.subplots(2, 2, figsize=(14, 10), layout='constrained')

    fig.suptitle(
        f'Сравнение оптимизаторов. Фон L_gray = {l_gray} | Loss_mode = {loss_mode} | Размер патча = {target_width}',
        fontsize=12
    )

    _, _, n_patch_screen, n_bg = jnd_model._compute_screen_geometry(L_patch=L_patch, target_width=target_width)

    start_La = min(np.min(L_patch), l_gray) if target_width != 'full' else np.min(L_patch)
    median = jnd_model.find_median(L_patch=L_patch, target_width=target_width)

    optimizers = [
        {
            'name': 'minimize_scalar'
        },
        {
            'name': 'L-BFGS-B',
            'params': {'x0': median}
        },
        {
            'name': 'log_grid_search'
        },
        {
            'name': 'oscillating_optimizer',
            'params': {
                'max_reversals': 5,
                'step': 0.1,
                'step_reduction': 5,
                'start_La': start_La,
                'max_iters': 100
            }
        }
    ]

    for idx, optimizer in enumerate(optimizers):
        ax = axes.flat[idx]

        optimization_results = jnd_model.find_La(
            L_patch,
            target_width=target_width, 
            loss_mode=loss_mode, 
            optimizer=optimizer['name'], 
            visualization=True,
            **optimizer.get('params', {})
        )

        optimization_results.optimization_visualization(ax=ax, x_log_scale=False)

        jnd_model.build_level_boundaries()

        uniform.append({
            'Средняя яркость патча': L_patch.mean(),
            '18% от макс яркости': 0.18 * max(np.max(L_patch), l_gray) if target_width != 'full' else 0.18 * np.max(L_patch),
            'Яркость фона': l_gray,
            'Оптимизатор': optimizer['name'],
            'optimize mode': loss_mode,
            'Размер патча, см': target_width,
            'Кол-во уровней': len(jnd_model.bounds),
            'La': jnd_model.La
        })

    category = 'uniform'

    save_dir = Path('results/plots') / category / f'L_gray_{l_gray}' / f'loss_mode_{loss_mode}' / f'target_width_{target_width}'
    save_dir.mkdir(parents=True, exist_ok=True)

    plt.savefig(save_dir / 'linear.png', dpi=300, bbox_inches='tight', pad_inches=0.2)

    for ax in axes.flat:
        ax.set_xscale('log')
        ax.set_xlabel('Яркость в логарифмическом масштабе')

    plt.savefig(save_dir / 'log.png', dpi=300, bbox_inches='tight', pad_inches=0.2)

    plt.close(fig)

In [137]:
df_bright = pd.DataFrame(bright)
df_dark = pd.DataFrame(dark)
df_uniform = pd.DataFrame(uniform)

df_bright.to_csv('results/bright.csv')
df_dark.to_csv('results/dark.csv')
df_uniform.to_csv('results/uniform.csv')

In [138]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [139]:
display(df_bright)

,Средняя яркость патча,Яркость фона,Оптимизатор,optimize mode,"Размер патча, см",Кол-во уровней,La
0,100.380605,30,minimize_scalar,abs,orig,17,30.000006
1,100.380605,30,L-BFGS-B,abs,orig,12,247.787274
2,100.380605,30,log_grid_search,abs,orig,12,244.745683
3,100.380605,30,oscillating_optimizer,abs,orig,17,30.000055
4,100.380605,30,minimize_scalar,abs,full,13,211.121441
5,100.380605,30,L-BFGS-B,abs,full,13,211.220996
6,100.380605,30,log_grid_search,abs,full,13,208.374527
7,100.380605,30,oscillating_optimizer,abs,full,13,211.042229
8,100.380605,30,minimize_scalar,abs,4,4,30.000005
9,100.380605,30,L-BFGS-B,abs,4,3,270.688882
10,100.380605,30,log_grid_search,abs,4,3,265.246857
11,100.380605,30,oscillating_optimizer,abs,4,4,30.000055
12,100.380605,30,minimize_scalar,abs,8,9,30.000001
13,100.380605,30,L-BFGS-B,abs,8,6,257.836703
14,100.380605,30,log_grid_search,abs,8,6,265.246857
15,100.380605,30,oscillating_optimizer,abs,8,9,30.000055
16,100.380605,30,minimize_scalar,abs,15,24,30.000002
17,100.380605,30,L-BFGS-B,abs,15,19,238.872915
18,100.380605,30,log_grid_search,abs,15,18,244.745683
19,100.380605,30,oscillating_optimizer,abs,15,24,30.000130
20,100.380605,30,minimize_scalar,square,orig,16,41.238685
21,100.380605,30,L-BFGS-B,square,orig,13,219.384366
22,100.380605,30,log_grid_search,square,orig,12,225.829064
23,100.380605,30,oscillating_optimizer,square,orig,16,33.492980
24,100.380605,30,minimize_scalar,square,full,14,150.039278
25,100.380605,30,L-BFGS-B,square,full,14,150.050948
26,100.380605,30,log_grid_search,square,full,14,151.044112
27,100.380605,30,oscillating_optimizer,square,full,14,150.011484
28,100.380605,30,minimize_scalar,square,4,4,30.301616
29,100.380605,30,L-BFGS-B,square,4,3,267.309813
30,100.380605,30,log_grid_search,square,4,3,265.246857
31,100.380605,30,oscillating_optimizer,square,4,4,30.301424
32,100.380605,30,minimize_scalar,square,8,9,31.270507
33,100.380605,30,L-BFGS-B,square,8,6,243.978629
34,100.380605,30,log_grid_search,square,8,6,244.745683
35,100.380605,30,oscillating_optimizer,square,8,9,31.270899
36,100.380605,30,minimize_scalar,square,15,20,193.466192
37,100.380605,30,L-BFGS-B,square,15,20,193.475950
38,100.380605,30,log_grid_search,square,15,20,192.269068
39,100.380605,30,oscillating_optimizer,square,15,20,193.516962
40,100.380605,60,minimize_scalar,abs,orig,15,59.999989
41,100.380605,60,L-BFGS-B,abs,orig,12,276.506592
42,100.380605,60,log_grid_search,abs,orig,12,265.246857
43,100.380605,60,oscillating_optimizer,abs,orig,15,59.999505
44,100.380605,60,minimize_scalar,abs,full,13,211.121441
45,100.380605,60,L-BFGS-B,abs,full,13,211.220996
46,100.380605,60,log_grid_search,abs,full,13,208.374527
47,100.380605,60,oscillating_optimizer,abs,full,13,211.042229
48,100.380605,60,minimize_scalar,abs,4,4,60.000002
49,100.380605,60,L-BFGS-B,abs,4,3,287.465317
50,100.380605,60,log_grid_search,abs,4,3,287.465317
51,100.380605,60,oscillating_optimizer,abs,4,4,59.999505
52,100.380605,60,minimize_scalar,abs,8,8,60.000007
53,100.380605,60,L-BFGS-B,abs,8,6,286.044175
54,100.380605,60,log_grid_search,abs,8,6,287.465317
55,100.380605,60,oscillating_optimizer,abs,8,8,59.999505
56,100.380605,60,minimize_scalar,abs,15,18,268.071129
57,100.380605,60,L-BFGS-B,abs,15,18,268.071158
58,100.380605,60,log_grid_search,abs,15,18,265.246857
59,100.380605,60,oscillating_optimizer,abs,15,23,59.999505
60,100.380605,60,minimize_scalar,square,orig,13,185.319674
61,100.380605,60,L-BFGS-B,square,orig,13,185.348834
62,100.380605,60,log_grid_search,square,orig,13,192.269068
63,100.380605,60,oscillating_optimizer,square,orig,14,79.342611
64,100.380605,60,minimize_scalar,square,full,14,150.039278
65,100.380605,60,L-BFGS-B,square,full,14,150.050948
66,100.380605,60,log_grid_search,square,full,14,151.044112
67,100.380605,60,oscillating_optimizer,square,full,14,150.011484
68,100.380605,60,minimize_scalar,square,4,4,60.476175
69,100.380605,60,L-BFGS-B,square,4,3,283.674272
70,100.380605,60,log_grid_search,square,4,3,287.465317
71,100.380605,60,oscillating_optimizer,square,4,4,60.476589
72,100.380605,60,minimize_scalar,square,8,6,231.155573
73,100.380605,60,L-BFGS-B,square,8,6,231.182025
74,100.380605,60,log_grid_search,square,8,6,225.829064
75,100.380605,60,oscillating_optimizer,square,8,8,61.958633
76,100.380605,60,minimize_scalar,square,15,20,158.553847
77,100.380605,60,L-BFGS-B,square,15,20,158.585332
78,100.380605,60,log_grid_search,square,15,20,163.696354
79,100.380605,60,oscillating_optimizer,square,15,20,158.559150
80,100.380605,90,minimize_scalar,abs,orig,14,90.000020
81,100.380605,90,L-BFGS-B,abs,orig,12,287.465317
82,100.380605,90,log_grid_search,abs,orig,12,287.465317
83,100.380605,90,oscillating_optimizer,abs,orig,14,90.003777
84,100.380605,90,minimize_scalar,abs,full,13,211.121441
85,100.380605,90,L-BFGS-B,abs,full,13,211.220996
86,100.380605,90,log_grid_search,abs,full,13,208.374527
87,100.380605,90,oscillating_optimizer,abs,full,13,211.042229
88,100.380605,90,minimize_scalar,abs,4,3,90.000001
89,100.380605,90,L-BFGS-B,abs,4,3,287.465317
90,100.380605,90,log_grid_search,abs,4,3,93.216450
91,100.380605,90,oscillating_optimizer,abs,4,3,90.003777
92,100.380605,90,minimize_scalar,abs,8,8,90.000001
93,100.380605,90,L-BFGS-B,abs,8,6,287.465317
94,100.380605,90,log_grid_search,abs,8,6,287.465317
95,100.380605,90,oscillating_optimizer,abs,8,8,90.003777
96,100.380605,90,minimize_scalar,abs,15,23,89.999991
97,100.380605,90,L-BFGS-B,abs,15,18,287.465317
98,100.380605,90,log_grid_search,abs,15,18,287.465317
99,100.380605,90,oscillating_optimizer,abs,15,23,90.003777
100,100.380605,90,minimize_scalar,square,orig,15,95.165187
101,100.380605,90,L-BFGS-B,square,orig,14,157.786993
102,100.380605,90,log_grid_search,square,orig,13,163.696354
103,100.380605,90,oscillating_optimizer,square,orig,14,114.325307
104,100.380605,90,minimize_scalar,square,full,14,150.039278
105,100.380605,90,L-BFGS-B,square,full,14,150.050948
106,100.380605,90,log_grid_search,square,full,14,151.044112
107,100.380605,90,oscillating_optimizer,square,full,14,150.011484
108,100.380605,90,minimize_scalar,square,4,3,90.662336
109,100.380605,90,L-BFGS-B,square,4,3,284.015618
110,100.380605,90,log_grid_search,square,4,3,93.216450
111,100.380605,90,oscillating_optimizer,square,4,3,90.667229
112,100.380605,90,minimize_scalar,square,8,8,92.556168
113,100.380605,90,L-BFGS-B,square,8,6,191.562214
114,100.380605,90,log_grid_search,square,8,8,93.216450
115,100.380605,90,oscillating_optimizer,square,8,8,95.559382
116,100.380605,90,minimize_scalar,square,15,21,145.655000
117,100.380605,90,L-BFGS-B,square,15,21,145.668742
118,100.380605,90,log_grid_search,square,15,21,151.044112
119,100.380605,90,oscillating_optimizer,square,15,21,145.648216

In [140]:
display(df_dark)

,Средняя яркость патча,Яркость фона,Оптимизатор,optimize mode,"Размер патча, см",Кол-во уровней,La
0,9.155383,30,minimize_scalar,abs,orig,14,86.518406
1,9.155383,30,L-BFGS-B,abs,orig,14,86.518397
2,9.155383,30,log_grid_search,abs,orig,14,82.378981
3,9.155383,30,oscillating_optimizer,abs,orig,17,29.999938
4,9.155383,30,minimize_scalar,abs,full,9,0.646166
5,9.155383,30,L-BFGS-B,abs,full,9,0.646167
6,9.155383,30,log_grid_search,abs,full,14,82.378981
7,9.155383,30,oscillating_optimizer,abs,full,9,0.646167
8,9.155383,30,minimize_scalar,abs,4,4,30.000003
9,9.155383,30,L-BFGS-B,abs,4,3,127.037987
10,9.155383,30,log_grid_search,abs,4,4,29.983085
11,9.155383,30,oscillating_optimizer,abs,4,4,30.000055
12,9.155383,30,minimize_scalar,abs,8,6,30.000000
13,9.155383,30,L-BFGS-B,abs,8,5,94.681842
14,9.155383,30,log_grid_search,abs,8,6,29.983085
15,9.155383,30,oscillating_optimizer,abs,8,6,30.000130
16,9.155383,30,minimize_scalar,abs,15,17,84.649325
17,9.155383,30,L-BFGS-B,abs,15,17,84.649330
18,9.155383,30,log_grid_search,abs,15,17,82.378981
19,9.155383,30,oscillating_optimizer,abs,15,17,84.647468
20,9.155383,30,minimize_scalar,square,orig,14,83.581179
21,9.155383,30,L-BFGS-B,square,orig,14,83.581263
22,9.155383,30,log_grid_search,square,orig,14,82.378981
23,9.155383,30,oscillating_optimizer,square,orig,14,83.581026
24,9.155383,30,minimize_scalar,square,full,10,1.214448
25,9.155383,30,L-BFGS-B,square,full,10,1.214440
26,9.155383,30,log_grid_search,square,full,14,82.378981
27,9.155383,30,oscillating_optimizer,square,full,10,1.214440
28,9.155383,30,minimize_scalar,square,4,3,115.131627
29,9.155383,30,L-BFGS-B,square,4,3,115.133015
30,9.155383,30,log_grid_search,square,4,3,118.190002
31,9.155383,30,oscillating_optimizer,square,4,3,115.626852
32,9.155383,30,minimize_scalar,square,8,5,93.045848
33,9.155383,30,L-BFGS-B,square,8,5,93.045914
34,9.155383,30,log_grid_search,square,8,5,95.174838
35,9.155383,30,oscillating_optimizer,square,8,5,93.047051
36,9.155383,30,minimize_scalar,square,15,17,81.636751
37,9.155383,30,L-BFGS-B,square,15,17,81.636809
38,9.155383,30,log_grid_search,square,15,17,82.378981
39,9.155383,30,oscillating_optimizer,square,15,17,81.636525
40,9.155383,60,minimize_scalar,abs,orig,14,80.721179
41,9.155383,60,L-BFGS-B,abs,orig,14,80.721162
42,9.155383,60,log_grid_search,abs,orig,14,82.378981
43,9.155383,60,oscillating_optimizer,abs,orig,14,80.728757
44,9.155383,60,minimize_scalar,abs,full,9,0.646166
45,9.155383,60,L-BFGS-B,abs,full,9,0.646167
46,9.155383,60,log_grid_search,abs,full,14,82.378981
47,9.155383,60,oscillating_optimizer,abs,full,9,0.646167
48,9.155383,60,minimize_scalar,abs,4,4,60.000008
49,9.155383,60,L-BFGS-B,abs,4,4,60.000000
50,9.155383,60,log_grid_search,abs,4,4,61.717021
51,9.155383,60,oscillating_optimizer,abs,4,4,59.999505
52,9.155383,60,minimize_scalar,abs,8,5,88.482787
53,9.155383,60,L-BFGS-B,abs,8,5,88.482785
54,9.155383,60,log_grid_search,abs,8,6,61.717021
55,9.155383,60,oscillating_optimizer,abs,8,6,59.999505
56,9.155383,60,minimize_scalar,abs,15,17,78.946022
57,9.155383,60,L-BFGS-B,abs,15,17,78.945987
58,9.155383,60,log_grid_search,abs,15,17,82.378981
59,9.155383,60,oscillating_optimizer,abs,15,17,78.946505
60,9.155383,60,minimize_scalar,square,orig,14,83.209461
61,9.155383,60,L-BFGS-B,square,orig,14,83.209505
62,9.155383,60,log_grid_search,square,orig,14,82.378981
63,9.155383,60,oscillating_optimizer,square,orig,14,83.203294
64,9.155383,60,minimize_scalar,square,full,10,1.214448
65,9.155383,60,L-BFGS-B,square,full,10,1.214440
66,9.155383,60,log_grid_search,square,full,14,82.378981
67,9.155383,60,oscillating_optimizer,square,full,10,1.214440
68,9.155383,60,minimize_scalar,square,4,3,94.536793
69,9.155383,60,L-BFGS-B,square,4,3,94.547554
70,9.155383,60,log_grid_search,square,4,3,95.174838
71,9.155383,60,oscillating_optimizer,square,4,3,94.535921
72,9.155383,60,minimize_scalar,square,8,5,90.794319
73,9.155383,60,L-BFGS-B,square,8,5,90.794354
74,9.155383,60,log_grid_search,square,8,5,88.546068
75,9.155383,60,oscillating_optimizer,square,8,5,90.797827
76,9.155383,60,minimize_scalar,square,15,17,81.393888
77,9.155383,60,L-BFGS-B,square,15,17,81.393944
78,9.155383,60,log_grid_search,square,15,17,82.378981
79,9.155383,60,oscillating_optimizer,square,15,17,81.394018
80,9.155383,90,minimize_scalar,abs,orig,14,90.000009
81,9.155383,90,L-BFGS-B,abs,orig,14,89.999999
82,9.155383,90,log_grid_search,abs,orig,14,88.546068
83,9.155383,90,oscillating_optimizer,abs,orig,14,89.998017
84,9.155383,90,minimize_scalar,abs,full,9,0.646166
85,9.155383,90,L-BFGS-B,abs,full,9,0.646167
86,9.155383,90,log_grid_search,abs,full,14,82.378981
87,9.155383,90,oscillating_optimizer,abs,full,9,0.646167
88,9.155383,90,minimize_scalar,abs,4,3,90.000003
89,9.155383,90,L-BFGS-B,abs,4,3,90.000000
90,9.155383,90,log_grid_search,abs,4,3,88.546068
91,9.155383,90,oscillating_optimizer,abs,4,3,90.003777
92,9.155383,90,minimize_scalar,abs,8,5,90.000015
93,9.155383,90,L-BFGS-B,abs,8,5,90.000000
94,9.155383,90,log_grid_search,abs,8,5,88.546068
95,9.155383,90,oscillating_optimizer,abs,8,5,90.003777
96,9.155383,90,minimize_scalar,abs,15,18,89.795914
97,9.155383,90,L-BFGS-B,abs,15,18,89.795934
98,9.155383,90,log_grid_search,abs,15,18,88.546068
99,9.155383,90,oscillating_optimizer,abs,15,18,89.794431
100,9.155383,90,minimize_scalar,square,orig,14,84.065523
101,9.155383,90,L-BFGS-B,square,orig,14,84.065516
102,9.155383,90,log_grid_search,square,orig,14,82.378981
103,9.155383,90,oscillating_optimizer,square,orig,14,84.070861
104,9.155383,90,minimize_scalar,square,full,10,1.214448
105,9.155383,90,L-BFGS-B,square,full,10,1.214440
106,9.155383,90,log_grid_search,square,full,14,82.378981
107,9.155383,90,oscillating_optimizer,square,full,10,1.214440
108,9.155383,90,minimize_scalar,square,4,3,93.026046
109,9.155383,90,L-BFGS-B,square,4,3,93.031087
110,9.155383,90,log_grid_search,square,4,3,95.174838
111,9.155383,90,oscillating_optimizer,square,4,3,93.026212
112,9.155383,90,minimize_scalar,square,8,5,91.183897
113,9.155383,90,L-BFGS-B,square,8,5,91.183912
114,9.155383,90,log_grid_search,square,8,5,88.546068
115,9.155383,90,oscillating_optimizer,square,8,5,91.187602
116,9.155383,90,minimize_scalar,square,15,17,82.168431
117,9.155383,90,L-BFGS-B,square,15,17,82.168434
118,9.155383,90,log_grid_search,square,15,17,82.378981
119,9.155383,90,oscillating_optimizer,square,15,17,82.167303

In [141]:
display(df_uniform)

,Средняя яркость патча,18% от макс яркости,Яркость фона,Оптимизатор,optimize mode,"Размер патча, см",Кол-во уровней,La
0,150.05,54.0,30,minimize_scalar,abs,orig,17,29.999995
1,150.05,54.0,30,L-BFGS-B,abs,orig,12,247.787274
2,150.05,54.0,30,log_grid_search,abs,orig,12,255.197480
3,150.05,54.0,30,oscillating_optimizer,abs,orig,17,30.000055
4,150.05,54.0,30,minimize_scalar,abs,full,12,253.928093
5,150.05,54.0,30,L-BFGS-B,abs,full,12,254.132939
6,150.05,54.0,30,log_grid_search,abs,full,12,255.197480
7,150.05,54.0,30,oscillating_optimizer,abs,full,12,254.139707
8,150.05,54.0,30,minimize_scalar,abs,4,12,30.000004
9,150.05,54.0,30,L-BFGS-B,abs,4,9,252.662051
10,150.05,54.0,30,log_grid_search,abs,4,9,255.197480
11,150.05,54.0,30,oscillating_optimizer,abs,4,12,30.000055
12,150.05,54.0,30,minimize_scalar,abs,8,37,29.999999
13,150.05,54.0,30,L-BFGS-B,abs,8,27,228.428179
14,150.05,54.0,30,log_grid_search,abs,8,27,235.371537
15,150.05,54.0,30,oscillating_optimizer,abs,8,37,30.000055
16,150.05,54.0,30,minimize_scalar,abs,15,67,198.455232
17,150.05,54.0,30,L-BFGS-B,abs,15,67,198.455210
18,150.05,54.0,30,log_grid_search,abs,15,67,200.220744
19,150.05,54.0,30,oscillating_optimizer,abs,15,86,30.000130
20,150.05,54.0,30,minimize_scalar,square,orig,17,31.061269
21,150.05,54.0,30,L-BFGS-B,square,orig,12,242.897374
22,150.05,54.0,30,log_grid_search,square,orig,12,235.371537
23,150.05,54.0,30,oscillating_optimizer,square,orig,17,31.060868
24,150.05,54.0,30,minimize_scalar,square,full,14,144.037016
25,150.05,54.0,30,L-BFGS-B,square,full,14,144.034963
26,150.05,54.0,30,log_grid_search,square,full,14,144.883631
27,150.05,54.0,30,oscillating_optimizer,square,full,14,144.038675
28,150.05,54.0,30,minimize_scalar,square,4,12,30.754655
29,150.05,54.0,30,L-BFGS-B,square,4,9,249.230003
30,150.05,54.0,30,log_grid_search,square,4,9,255.197480
31,150.05,54.0,30,oscillating_optimizer,square,4,12,30.754983
32,150.05,54.0,30,minimize_scalar,square,8,28,212.860447
33,150.05,54.0,30,L-BFGS-B,square,8,28,212.868357
34,150.05,54.0,30,log_grid_search,square,8,28,217.085845
35,150.05,54.0,30,oscillating_optimizer,square,8,36,41.869105
36,150.05,54.0,30,minimize_scalar,square,15,71,145.054137
37,150.05,54.0,30,L-BFGS-B,square,15,71,145.053341
38,150.05,54.0,30,log_grid_search,square,15,71,144.883631
39,150.05,54.0,30,oscillating_optimizer,square,15,71,144.928794
40,150.05,54.0,60,minimize_scalar,abs,orig,15,60.000009
41,150.05,54.0,60,L-BFGS-B,abs,orig,12,276.506593
42,150.05,54.0,60,log_grid_search,abs,orig,12,276.693411
43,150.05,54.0,60,oscillating_optimizer,abs,orig,15,59.999505
44,150.05,54.0,60,minimize_scalar,abs,full,12,253.928093
45,150.05,54.0,60,L-BFGS-B,abs,full,12,254.132939
46,150.05,54.0,60,log_grid_search,abs,full,12,255.197480
47,150.05,54.0,60,oscillating_optimizer,abs,full,12,254.139707
48,150.05,54.0,60,minimize_scalar,abs,4,12,59.999989
49,150.05,54.0,60,L-BFGS-B,abs,4,9,281.129622
50,150.05,54.0,60,log_grid_search,abs,4,9,276.693411
51,150.05,54.0,60,oscillating_optimizer,abs,4,12,59.999505
52,150.05,54.0,60,minimize_scalar,abs,8,35,59.999998
53,150.05,54.0,60,L-BFGS-B,abs,8,27,258.222052
54,150.05,54.0,60,log_grid_search,abs,8,27,255.197480
55,150.05,54.0,60,oscillating_optimizer,abs,8,35,59.999505
56,150.05,54.0,60,minimize_scalar,abs,15,65,230.222362
57,150.05,54.0,60,L-BFGS-B,abs,15,65,230.222340
58,150.05,54.0,60,log_grid_search,abs,15,64,235.371537
59,150.05,54.0,60,oscillating_optimizer,abs,15,81,59.999505
60,150.05,54.0,60,minimize_scalar,square,orig,15,61.339801
61,150.05,54.0,60,L-BFGS-B,square,orig,12,255.777371
62,150.05,54.0,60,log_grid_search,square,orig,12,255.197480
63,150.05,54.0,60,oscillating_optimizer,square,orig,15,61.340618
64,150.05,54.0,60,minimize_scalar,square,full,14,144.037016
65,150.05,54.0,60,L-BFGS-B,square,full,14,144.034963
66,150.05,54.0,60,log_grid_search,square,full,14,144.883631
67,150.05,54.0,60,oscillating_optimizer,square,full,14,144.038675
68,150.05,54.0,60,minimize_scalar,square,4,12,60.962273
69,150.05,54.0,60,L-BFGS-B,square,4,9,266.545080
70,150.05,54.0,60,log_grid_search,square,4,9,276.693411
71,150.05,54.0,60,oscillating_optimizer,square,4,12,60.961523
72,150.05,54.0,60,minimize_scalar,square,8,28,192.814325
73,150.05,54.0,60,L-BFGS-B,square,8,28,192.896933
74,150.05,54.0,60,log_grid_search,square,8,28,200.220744
75,150.05,54.0,60,oscillating_optimizer,square,8,35,65.268344
76,150.05,54.0,60,minimize_scalar,square,15,73,123.763698
77,150.05,54.0,60,L-BFGS-B,square,15,73,123.757268
78,150.05,54.0,60,log_grid_search,square,15,73,123.246459
79,150.05,54.0,60,oscillating_optimizer,square,15,73,123.759265
80,150.05,54.0,90,minimize_scalar,abs,orig,14,89.999996
81,150.05,54.0,90,L-BFGS-B,abs,orig,12,300.000000
82,150.05,54.0,90,log_grid_search,abs,orig,12,300.000000
83,150.05,54.0,90,oscillating_optimizer,abs,orig,14,90.003777
84,150.05,54.0,90,minimize_scalar,abs,full,12,253.928093
85,150.05,54.0,90,L-BFGS-B,abs,full,12,254.132939
86,150.05,54.0,90,log_grid_search,abs,full,12,255.197480
87,150.05,54.0,90,oscillating_optimizer,abs,full,12,254.139707
88,150.05,54.0,90,minimize_scalar,abs,4,11,89.999987
89,150.05,54.0,90,L-BFGS-B,abs,4,9,300.000000
90,150.05,54.0,90,log_grid_search,abs,4,9,300.000000
91,150.05,54.0,90,oscillating_optimizer,abs,4,11,90.003777
92,150.05,54.0,90,minimize_scalar,abs,8,33,89.999994
93,150.05,54.0,90,L-BFGS-B,abs,8,26,283.442870
94,150.05,54.0,90,log_grid_search,abs,8,26,276.693411
95,150.05,54.0,90,oscillating_optimizer,abs,8,33,90.003777
96,150.05,54.0,90,minimize_scalar,abs,15,63,257.912512
97,150.05,54.0,90,L-BFGS-B,abs,15,63,257.912501
98,150.05,54.0,90,log_grid_search,abs,15,63,255.197480
99,150.05,54.0,90,oscillating_optimizer,abs,15,77,95.559382
100,150.05,54.0,90,minimize_scalar,square,orig,14,91.229166
101,150.05,54.0,90,L-BFGS-B,square,orig,12,246.638899
102,150.05,54.0,90,log_grid_search,square,orig,14,89.183539
103,150.05,54.0,90,oscillating_optimizer,square,orig,14,91.231333
104,150.05,54.0,90,minimize_scalar,square,full,14,144.037016
105,150.05,54.0,90,L-BFGS-B,square,full,14,144.034963
106,150.05,54.0,90,log_grid_search,square,full,14,144.883631
107,150.05,54.0,90,oscillating_optimizer,square,full,14,144.038675
108,150.05,54.0,90,minimize_scalar,square,4,11,90.900444
109,150.05,54.0,90,L-BFGS-B,square,4,9,267.875218
110,150.05,54.0,90,log_grid_search,square,4,11,89.183539
111,150.05,54.0,90,oscillating_optimizer,square,4,11,90.899523
112,150.05,54.0,90,minimize_scalar,square,8,33,93.224005
113,150.05,54.0,90,L-BFGS-B,square,8,30,141.706834
114,150.05,54.0,90,log_grid_search,square,8,33,96.695695
115,150.05,54.0,90,oscillating_optimizer,square,8,33,95.559382
116,150.05,54.0,90,minimize_scalar,square,15,74,119.206034
117,150.05,54.0,90,L-BFGS-B,square,15,74,119.223208
118,150.05,54.0,90,log_grid_search,square,15,73,123.246459
119,150.05,54.0,90,oscillating_optimizer,square,15,74,119.203305